class vehicles_ef : vehicles_base
{
    ITEM(EF_B_MRAP_01_LAAD_MJTF_Des, 12500, "AA", VEHICLE_CONDITION_AA);
    ITEM(EF_B_AAV9_MJTF_Des, 33910, "APC", VEHICLE_CONDITION_APC);
    ITEM(EF_B_AAV9_50mm_MJTF_Des, 35710, "APC", VEHICLE_CONDITION_APC);
    ITEM(EF_B_AAV9_MJTF_Wdl, 33910, "APC", VEHICLE_CONDITION_APC);
    ITEM(EF_B_AAV9_50mm_MJTF_Wdl, 35710, "APC", VEHICLE_CONDITION_APC);
    ITEM(EF_B_MRAP_01_AT_MJTF_Des, 7620, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(EF_B_MRAP_01_FSV_MJTF_Des, 7620, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
    ITEM(EF_B_CombatBoat_AT_MJTF_Des, 5700, "BOAT", VEHICLE_CONDITION_BOAT);
    ITEM(EF_B_CombatBoat_HMG_MJTF_Des, 5700, "BOAT", VEHICLE_CONDITION_BOAT);
    ITEM(EF_B_CombatBoat_Unarmed_MJTF_Des, 2100, "BOAT", VEHICLE_CONDITION_BOAT);
    ITEM(EF_B_LCC_MJTF_Des, 9100, "BOAT", VEHICLE_CONDITION_BOAT);
    ITEM(EF_B_LCC_SideLoad_MJTF_Des, 9100, "BOAT", VEHICLE_CONDITION_BOAT);
    ITEM(EF_B_AH99J_MJTF_Des, 49400, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(EF_B_Heli_Attack_01_dynamicLoadout_MJTF_Des, 12900, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(EF_B_Heli_Transport_01_MJTF_Des, 10500, "HELI", VEHICLE_CONDITION_HELI);
    ITEM(EF_LPD_Turret_1_MJTF_Des, 15000, "STATICAA", VEHICLE_CONDITION_STATICAA);
};
